; mydefrag-syntax.ini
; MyDefrag Preprocessor configuration

debugOn=true
verboseLevel=5
referenceRelativePathLevel=Error
referenceContainsMacros=3
referenceFileFoundLevel=3
referenceFileNotFoundLevel=1
bob=Sample
