; mydefrag-syntax.ini
; MyDefrag Preprocessor configuration

debugOn=false
verboseLevel=2
referenceRelativePathLevel=Error
referenceContainsMacros=3
fileReferenceFoundLevel=3
fileReferenceNotFoundLevel=1
bob=Sample
